# Generated by Django 6.0.7 on 2026-07-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Swagcitybymercy', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Quality, luxury female apparel — Lagos, Nigeria.', max_length=255)),
                ('about_text', models.TextField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Digits only with country code, e.g. 2348012345678', max_length=30)),
                ('instagram_handle', models.CharField(blank=True, default='swagcitybymercy', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('lagos_delivery_note', models.CharField(blank=True, default='1-2 working days within Lagos', max_length=255)),
                ('other_regions_delivery_note', models.CharField(blank=True, default='5-7 working days for other regions in Nigeria', max_length=255)),
                ('international_delivery_note', models.CharField(blank=True, default='5-6 working days for international orders', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
