# Generated by Django 6.0.7 on 2026-07-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Shown in the site header, footer, and browser tab icon. Square images work best.', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, help_text='Longer site description, shown on the About page and homepage.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, default='Quality, luxury female apparel — Lagos, Nigeria.', help_text='Short slogan/motto shown in the header area, browser tab, and search results.', max_length=255),
        ),
    ]
