# Generated by Django 6.0.7 on 2026-07-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_sitesettings_logo_alter_sitesettings_about_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ item',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('returns', 'Return & Refund Policy'), ('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(help_text='Supports basic HTML (paragraphs, lists, bold, links).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
    ]
